version: '3.4'

networks:
  my_net:
    driver: bridge

services: 
  webapplication2:    
    # image: ${DOCKER_REGISTRY-}webapplication2
    # build:
    #   context: WebApplication2
    #   dockerfile: Dockerfile
    image: ericyuh/webapplication2:latest   
    networks:
      my_net:
    environment:
      - MSSQL_SA_PASSWORD=c22NaBpYk9Nsm_Zn
    ports:
      - "8080:8080"    
    depends_on:
      - docker-demo-sqlserver
  docker-demo-sqlserver:
    container_name: docker-demo-sqlserver-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    hostname: docker-demo-sqlserver    
    networks:
      my_net:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=c22NaBpYk9Nsm_Zn
    ports:
      - "4433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql/data